### ISSUE TITLE
ESP01 socket example

### ISSUE THREAD

**Issue by meeDamian** [CytronTechnologies/MAKER-PI-PICO#1]
It would be really nice if you've had even the most rudimentary example on how to use pico with ESP01 through the socket on maker board.

**Comment by ckuehnel** [comment]
I played around with Maker Pi Pico board. It supports prototyping very well. My next step is internet connection. Therefore, the same question as meeDamian. Is there a webserver example or similar using ESP-01 w/ AT commands?

**Comment by kiate** [comment]
Please have a look at this tutorial 
https://tutorial.cytron.io/2021/03/31/program-maker-pi-pico-and-esp01-with-blynk-iot-app-using-arduino-ide/

**Comment by flashypepo** [comment]
[Tinker Tech Trove](https://youtu.be/v_Tm_IgbRDc) does have two very nice tutorials on YouTube, how to use ESP-01 and Raspberry PI PICO. Give it a try.

Some adoptions has to be made using the Maker PI PICO board, but was trivial (UART port). I've done his first tutorial, it is working, and currently working on his second tutorial. He makes use of Arduino code on ESP-01 and Micropython on PI PICO. No AT-commands are used back-and-forth. I'm using CircuitPython on PI PICO, so expect modifications. Soon I'll publish in a blog and github, what I've done. 

PS. The Maker PI PICO is a very nice board, a little bit overwhelming perhaps, but supports nice prototyping facilities, like Grove connectors, audio, SD-card and ... ESP-01/Wifi for web-access.

**Comment by waiweng83** [comment]
We've added examples for CircuitPython [here](https://github.com/CytronTechnologies/MAKER-PI-PICO/tree/main/Example%20Code/CircuitPython/IoT).
However, please take note that the Telegram example only works with AT Firmware V2.2.0.
If you are able to update the firmware by yourself, you can download it [here](https://drive.google.com/file/d/1q4QLJlIWHVQznaWsVvPev9ZW9vRHr1F8/view?usp=sharing).

**Comment by andypiper** [comment]
Reading the comments, these require an ESP8266, not an ESP-01?

**Comment by waiweng83** [comment]
> Reading the comments, these require an ESP8266, not an ESP-01?

ESP-01 is the module while ESP8266 is referring to the chip used in ESP-01. Thus it's compatible with ESP-01.

**Comment by h3retek** [comment]
I had to use a different method for flashing the[ ESP-01_AT_Firmware_V2.2.0](https://drive.google.com/file/d/1q4QLJlIWHVQznaWsVvPev9ZW9vRHr1F8/view?usp=sharing)

**Comment by stuatb** [comment]
Have been trying use ESP-01 with maker pi pico - finally had sucess using ESP_AT_Lib on arduino!
see sample HTTPGET example:

[](https://github.com/stuatb/maker-pi-pico/blob/main/HTTPGET.ino)
