### ISSUE TITLE
update the firmware of the ESP-01

### ISSUE THREAD

**Issue by h3retek** [CytronTechnologies/MAKER-PI-PICO#3]
This here link: https://www.elec-cafe.com/esp8266-esp-01-firmware-update/

Is dead?

**Comment by h3retek** [comment]
With thanks to the internet, especially [TheMakerThailand](http://www.themakerthailand.com/article/14/%E0%B8%81%E0%B8%B2%E0%B8%A3-update-firmware-%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A-esp01)

0. Using [ESP Link](https://th.cytron.io/c-wireless-devices/p-esp01-usb-programmer-adapter) and [ESP-01](https://th.cytron.io/p-esp-01-wifi-serial-transceiver-module-esp8266)
1. Download [Espressif](https://github.com/espressif/ESP8266_NONOS_SDK/archive/refs/tags/v3.0.zip) & unzip. In here you will find the first 5 files needed (`\ESP8266_NONOS_SDK-3.0.4\bin\`)
2. Download the relevant AT firmware [here](https://github.com/CytronTechnologies/MAKER-PI-PICO/tree/main/Example%20Code/CircuitPython/IoT)
3. Download and run [Flash Downloads tool](https://www.espressif.com/sites/default/files/tools/flash_download_tool_v3.8.8_0.zip)
3. a) Before adding anything, after plugging in the ESP Link with the ESP-01 inserted, click START to scan the ESP for this

![image](https://user-images.githubusercontent.com/69946004/127732632-3d1a6945-542a-49a1-9e56-9cfa59b0abf9.png)

4. Setup (your COM port might differ)

![image](https://user-images.githubusercontent.com/69946004/127732438-7c7077f8-3dbc-4841-a4e1-4003a51a4f85.png)

5. Click START again, and wait . . .

6. After it is FINISH'ed, unplug, and connect to your MC.

Good luck with the rest.

**Comment by h3retek** [comment]
no, it's not

**Comment by h3retek** [comment]
With thanks to the internet, especially [TheMakerThailand](http://www.themakerthailand.com/article/14/%E0%B8%81%E0%B8%B2%E0%B8%A3-update-firmware-%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A-esp01)

0. Using [ESP Link](https://th.cytron.io/c-wireless-devices/p-esp01-usb-programmer-adapter) and [ESP-01](https://th.cytron.io/p-esp-01-wifi-serial-transceiver-module-esp8266)
1. Download [Espressif ESP8266 NONOS SDK source code](https://github.com/espressif/ESP8266_NONOS_SDK/releases) & unzip. In here you will find the first 4 files needed (`\ESP8266_NONOS_SDK-X.X.X\bin\`)
2. Download the relevant AT firmware [here](https://github.com/CytronTechnologies/MAKER-PI-PICO/tree/main/Example%20Code/CircuitPython/IoT)
3. Download and run [Flash Downloads tool](https://www.espressif.com/sites/default/files/tools/flash_download_tool_v3.8.8_0.zip)
3. a) Before adding anything, after plugging in the ESP Link with the ESP-01 inserted, click START to scan the ESP for this

![image](https://user-images.githubusercontent.com/69946004/127732632-3d1a6945-542a-49a1-9e56-9cfa59b0abf9.png)

4. Setup (your COM port might differ)

![image](https://user-images.githubusercontent.com/69946004/127734806-0347b7bb-d8c4-419f-b675-bde467579f6b.png)

5. Click START again, and wait . . .

6. After it is FINISH'ed, unplug, and connect to your MC.

Good luck with the rest.

**Comment by h3retek** [comment]
This works with the [Cytron Maker Pi RP2040](https://th.cytron.io/p-maker-pi-rp2040-simplifying-robotics-with-raspberry-pi-rp2040), but you have to put 3.3 V on the EN pin.

**Comment by waiweng83** [comment]
> With thanks to the internet, especially [TheMakerThailand](http://www.themakerthailand.com/article/14/%E0%B8%81%E0%B8%B2%E0%B8%A3-update-firmware-%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A-esp01)
> 
> 1. Using [ESP Link](https://th.cytron.io/c-wireless-devices/p-esp01-usb-programmer-adapter) and [ESP-01](https://th.cytron.io/p-esp-01-wifi-serial-transceiver-module-esp8266)
> 2. Download [Espressif ESP8266 NONOS SDK source code](https://github.com/espressif/ESP8266_NONOS_SDK/releases) & unzip. In here you will find the first 4 files needed (`\ESP8266_NONOS_SDK-X.X.X\bin\`)
> 3. Download the relevant AT firmware [here](https://github.com/CytronTechnologies/MAKER-PI-PICO/tree/main/Example%20Code/CircuitPython/IoT)
> 4. Download and run [Flash Downloads tool](https://www.espressif.com/sites/default/files/tools/flash_download_tool_v3.8.8_0.zip)
> 5. a) Before adding anything, after plugging in the ESP Link with the ESP-01 inserted, click START to scan the ESP for this
> 
> ![image](https://user-images.githubusercontent.com/69946004/127732632-3d1a6945-542a-49a1-9e56-9cfa59b0abf9.png)
> 
> 1. Setup (your COM port might differ)
> 
> ![image](https://user-images.githubusercontent.com/69946004/127734806-0347b7bb-d8c4-419f-b675-bde467579f6b.png)
> 
> 1. Click START again, and wait . . .
> 2. After it is FINISH'ed, unplug, and connect to your MC.
> 
> Good luck with the rest.

Thanks for pointing out an alternative method to update the firmware.
Anyway, if you are using this method, you only need to program the one binary file to address 0x00.

**Comment by h3retek** [comment]
Ok Thanks. I assumed the `esp_init_data_default_v08.bin` contained necessary startup code for the ESP.

**Comment by kiate** [comment]
> Ok Thanks. I assumed the `esp_init_data_default_v08.bin` contained necessary startup code for the ESP.

The correct file should be `ESP-01_AT_Firmware_V2.2.0.bin` @ 0x00000
