### ISSUE TITLE
MicroPython SD Card Examole

### ISSUE THREAD

**Issue by PeteHollyer** [CytronTechnologies/MAKER-PI-PICO#4]
I NEED a MICROPYTHON SD Card example for the Maker-Pi-Pico.  
I have tried all the "current" examples on the internet I can find and NONE of them Work.
All of the Die on the "VfsFat" command

My SDCard and the Reader Work perfectly using CircuitPython, just NOT with MicroPython. I've tried formatting block size 512 & 1024 FS Fat32, Win 10 Formatter; Same error both times.

# Code
`
import machine
import sdcard
import uos

cs = machine.Pin(15, machine.Pin.OUT)

spi = machine.SPI(1,
                  baudrate=1000000,
                  polarity=0,
                  phase=0,
                  bits=8,
                  firstbit=machine.SPI.MSB,
                  sck=machine.Pin(10),
                  mosi=machine.Pin(11),
                  miso=machine.Pin(12))

# Initialize SD card
sd = sdcard.SDCard(spi, cs)

vfs = vos.VfsFat(sd)                                          #<====   DIES HERE
uos.mount(vfs, "/sd")

with open("/sd/test01.txt", "w") as file:
    file.write("Hello, SD World!\r\n")
    file.write("This is a test\r\n")

# Open the file we just created and read from it
with open("/sd/test01.txt", "r") as file:
    data = file.read()
    print(data)
`

# with following error

Traceback (most recent call last):
  File "<stdin>", line 23, in <module>
  File "sdcard.py", line 238, in readblocks
OSError: [Errno 5] EIO

Thx
Pete

**Comment by PeteHollyer** [comment]
I Tracked into the problem, 

Micropython was NOT liking my SD card.  Even though Circuitpython liked it.
I changed cards to a 32 GB card ( was a 2 BG Card)  and it read.

`
from machine import Pin, SPI
import sdcard
import os
    
def OpenSD():
    sd_spi = SPI(1, sck = Pin(10, Pin.OUT), mosi = Pin(11, Pin.OUT), miso = Pin(12, Pin.OUT))
    # Create SDCard object
    sd = sdcard.SDCard(sd_spi, Pin(15, Pin.OUT))
    os.mount(sd, "/sd")
    os.listdir("/sd")
    print("Mounted")

def CloseSD():
    os.umount("/sd")
    print("UMount")
`

Proble was ALL mine! Sorry.
Please Close Issue

**Comment by designdevy** [comment]
hi can you share the circuitpython example that works with make pi pico? @PeteHollyer

**Comment by sgbaird** [comment]
I think you have [a typo](https://github.com/CytronTechnologies/MAKER-PI-PICO/issues/4#issue-1000117937):
`vfs = vos.VfsFat(sd)` --> `vfs = uos.VfsFat(sd)`

Thanks for the MicroPython script.

**Comment by sgbaird** [comment]
@PeteHollyer did you ever figure out the formatting with your other card that wasn't working?

**Comment by PeteHollyer** [comment]
Yes I believe I Did..

Thanks

Pete

Sent from Mail for Windows
