### ISSUE TITLE
ESP8266 Grove example

### ISSUE THREAD

**Issue by jliu70** [CytronTechnologies/MAKER-PI-PICO#5]
Hi,

I'm trying to use the new Cytron Grove ESP8266 module with the Maker Pi Pico with CircuitPython 6.3.0

I connected it to "Grove 5" port and modified the code to use GP9 and GP8
(The same occurs when I connect to "Grove 1" port and use GP1 and GP0.)

```
# Initialize UART connection to the ESP8266 WiFi Module.
RX = board.GP9
TX = board.GP8
uart = busio.UART(TX, RX, receiver_buffer_size=2048)  # Use large buffer as we're not using hardware flow control.

esp = adafruit_espatcontrol.ESP_ATcontrol(uart, 115200, debug=False)

wifi = adafruit_espatcontrol_wifimanager.ESPAT_WiFiManager(esp, secrets)
```

However, the program, while it can connect to WiFI and ping google.com, is unable to retrieve text from a webpage.

```

code.py output:
Resetting ESP module
Connecting to WiFi...
Connected!
My Grove ESP8266 IP address: 192.168.1.187
ESP Firmware Version: AT version:2.2.0.0(b097cdf - ESP8266 - Jun 17 2021 12:57:45)
Ping google.com: 10 ms
----------------------------------------
Ping wifitest.adafruit.com: 10 ms
----------------------------------------
----------------------------------------
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
---> AT+CIPDOMAIN="wifitest.adafruit.com"
<--- b'+CIPDOMAIN:"104.236.193.178"\r\n\r\nOK\r\n'
---> AT+CIPSTATUS
<--- b'STATUS:2\r\n\r\nOK\r\n'
---> AT+CIPSTART="TCP","104.236.193.178",80,10
<--- b'CONNECT\r\n\r\nOK\r\n'
---> AT+CIPSTATUS
<--- b'STATUS:3\r\n+CIPSTATUS:0,"TCP","104.236.193.178",80,49836,0\r\n\r\nOK\r\n'
---> AT+CIPSEND=3
<--- b'\r\nOK\r\n\r\n>'
Failed, retrying
 No OK response to AT+CIPSEND=3
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
---> AT+CIPDOMAIN="wifitest.adafruit.com"
<--- b'\r\nbusy p...\r\n\r\nRecv 3 bytes\r\n\r\nSEND OK\r\n'
Traceback (most recent call last):
  File "code.py", line 124, in <module>
  File "adafruit_requests.py", line 698, in get
  File "adafruit_requests.py", line 556, in request
  File "adafruit_requests.py", line 414, in _get_socket
  File "adafruit_espatcontrol/adafruit_espatcontrol_socket.py", line 26, in getaddrinfo
  File "adafruit_espatcontrol/adafruit_espatcontrol.py", line 413, in nslookup
RuntimeError: Couldn't find IP address

Code done running.
```

Any thoughts or suggestions?

Thanks,
Jeff

**Comment by mlhakimz** [comment]
It seems like using the latest adafruit_espatcontrol.py from Adafruit's repository will throw an error regardless of CircuitPython version (7.0 or 6.3). I was using adafruit_espatcontrol.py from Cytron's repository and it's working.

After some digging, I found that on line 526,

`response += self._uart.read(self._uart.in_waiting)`
Doesn't work. - [(Latest Adafruit version)](https://github.com/adafruit/Adafruit_CircuitPython_ESP_ATcontrol/blob/5f4b8407d5f654c64982e7507e3e95ae2fa1d3ff/adafruit_espatcontrol/adafruit_espatcontrol.py#L526)

`response += self._uart.read(1)`
Works fine. - [(Older version)](https://github.com/CytronTechnologies/MAKER-PI-PICO/blob/main/Example%20Code/CircuitPython/IoT/lib/adafruit_espatcontrol/adafruit_espatcontrol.py#L526
)

Hope this helps.

**Comment by waiweng83** [comment]
There was a bug in Adafruit CircuitPython Libraries and should be fixed now.

https://github.com/adafruit/Adafruit_CircuitPython_ESP_ATcontrol/issues/43
