### ISSUE TITLE
Need MicroPython Example Code for Reading and Writing to the SD Card

### ISSUE THREAD

**Issue by dmccreary** [CytronTechnologies/MAKER-PI-PICO#6]
Thank you for this excellent board and the great example code.  I am developing materials for CoderDojo classes.

Do you have any sample MicroPython code for reading or writing to the SD Card?

Hi have tried various examples but I can't see to find an example that works.

Here is the sdcard.py driver:

https://github.com/micropython/micropython/blob/master/drivers/sdcard/sdcard.py

Here is my example:

```
import machine, sdcard, os

SDCARD_SCK = 10
SDCARD_SDI = 11
SDCARD_SD0 = 12
SDCARD_X1 = 13
SDCARD_X2 = 14
SDCARD_CSn = 15

# SPI setup
spi_sck=machine.Pin(SDCARD_SCK)
spi_tx=machine.Pin(SDCARD_SDI)
spi=machine.SPI(1,baudrate=100000,sck=spi_sck, mosi=spi_tx)
sd = sdcard.SDCard(spi=spi, cs=machine.Pin(SDCARD_CSn))
os.mount(sd, '/sd')
os.listdir('/')
```

Which returns:

Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
  File "/lib/sdcard.py", line 54, in __init__
  File "/lib/sdcard.py", line 82, in init_card
OSError: no SD card

**Comment by kiate** [comment]
Hi @dmccreary,

I think the main issue could be due to the microSD pinout table at the back of the board. Actually the SD & SPI function columns are referring to the SD card. Hence MOSI should be on GP11 and MISO is on GP12. So sorry for the confusion!

This code works fine with my board here... 
```
import machine, os, sdcard

# Assign chip select (CS) pin (and start it high)
cs = machine.Pin(15, machine.Pin.OUT)
# Intialize SPI peripheral (start with 1 MHz)
spi = machine.SPI(1,
                  baudrate=1000000,
                  polarity=0,
                  phase=0,
                  bits=8,
                  firstbit=machine.SPI.MSB,
                  sck=machine.Pin(10),
                  mosi=machine.Pin(11),
                  miso=machine.Pin(12))
# Initialize SD card
sd = sdcard.SDCard(spi, cs)

# OR this simpler initialization code should works on Maker Pi Pico too...
#sd = sdcard.SDCard(machine.SPI(1), machine.Pin(15))

os.mount(sd, '/sd')
# check the content
os.listdir('/sd')

# try some standard file operations
file = open('/sd/test.txt', 'w')
file.write('Testing SD card on Maker Pi Pico')
file.close()
file = open('/sd/test.txt', 'r')
data = file.read()
print(data)
file.close()
```
