### ISSUE TITLE
Connected to None

### ISSUE THREAD

**Issue by designdevy** [CytronTechnologies/MAKER-PI-PICO#8]
After following the simpletest.py file, I get stuck at this error
![image](https://user-images.githubusercontent.com/13625702/149006542-4f758f49-e917-4848-8f3a-ceac91dfaf04.png)

**Comment by waiweng83** [comment]
Did you change the WiFi SSID and password in secrets.py and copy it to the Maker Pi Pico?

**Comment by designdevy** [comment]
![image](https://user-images.githubusercontent.com/13625702/149073548-7a8f109d-618a-4f6f-bec3-2fef2c69275a.png)
![image](https://user-images.githubusercontent.com/13625702/149073567-a77c69f1-6e28-4065-9b19-b30ba3fe9f2b.png)

**Comment by designdevy** [comment]
https://github.com/adafruit/Adafruit_CircuitPython_ESP_ATcontrol/releases/tag/0.6.1

**Comment by designdevy** [comment]
still stuck. seems like the updated library requires to have a hard reset pin which maker pi pico doesn't expose for the esp socket

**Comment by designdevy** [comment]
fixed by flashing the cytron at firmware again
