### ISSUE TITLE
Out of Box demo hangs in check_SDCARD for CircuitPython

### ISSUE THREAD

**Issue by jerryneedell** [CytronTechnologies/MAKER-PI-PICO#9]
With the latest release of CircuitPython, the demo hangs if button 2 is pressed to test the SDCard

It works fine if the order if the "deinit" of the spi bus and the sdcard are swapped here:
https://github.com/CytronTechnologies/MAKER-PI-PICO/blob/main/Out-of-the-box%20Demo%20Code/CircuitPython/code.py#L438

doing sd.deinit()  before spi.deinit() works 

I ran into this on CircuitPython 7.2.0-alpha1 but I don't know when it first became a problem.
I opened an issue in CircuitPython regarding the hang but it may make more sense to d the spi.deinit() after the sd.deinit() an general. Here is a link to the issue in CircuitPython for your reference.
https://github.com/adafruit/circuitpython/issues/5869

**Comment by kiate** [comment]
Thank you so much for pointing this out @jerryneedell !
